### ISSUE TITLE
List in Desktop Site

### ISSUE THREAD

**Issue by samarsault** [FOSSASIA-Web/gci14.fossasia.org#83]
According to the latest update, https://github.com/fossasia/fossasia.github.io/pull/81. 
A list appears below the footer of the site which I guess is not needed. We could do something like 

``` css
display:none
```

if the app is run on the desktop

![screen shot 2014-12-17 at 6 49 57 pm](https://cloud.githubusercontent.com/assets/2987087/5471609/be9af5c2-861d-11e4-8fc8-2a86925189af.png)

But the mobile version works as it is supposed to.

**Comment by roonyh** [comment]
@samarjeet27 @XTremeRox a pull request is most welcome!

**Comment by XTremeRox** [comment]
I had created 2 divs because I have not made any changes using jquery, we could rather change the class name using jquery ("class" of the Menu items), RoonyH, you could put up a task for that, by the way, can't do that, else the menu would not showup,  if I got you correct, check it by hosting it and then open the page in your mobile.
